import { describe, expect, it } from 'vitest'
import { correctExerciseInstructions } from './exercise-instructions.js'

describe('exercise instruction corrections', () => {
  it.each([
    ['0979', 'Attach the band to a sturdy anchor point at waist height.', 'Attach the band to a sturdy anchor point at chest height.'],
    ['0979', 'Sujeta la banda a un punto de anclaje resistente a la altura de la cintura.', 'Sujeta la banda a un punto de anclaje resistente a la altura del pecho.'],
    ['0979', "Fixe l'élastique à un point d'ancrage solide à hauteur de la taille.", "Fixe l'élastique à un point d'ancrage solide à hauteur de poitrine."],
    ['0979', 'बैंड को कमर की ऊंचाई पर एक मजबूत एंकर पॉइंट से जोड़ें।', 'बैंड को छाती की ऊंचाई पर एक मजबूत एंकर पॉइंट से जोड़ें।'],
    ['0979', "Attacca la fascia a un punto di ancoraggio robusto all'altezza della vita.", "Attacca la fascia a un punto di ancoraggio robusto all'altezza del petto."],
    ['0979', '밴드를 허리 높이의 견고한 고정점에 부착합니다.', '밴드를 가슴 높이의 견고한 고정점에 부착합니다.'],
    ['0979', 'Przymocuj taśmę do stabilnego punktu zaczepienia na wysokości talii.', 'Przymocuj taśmę do stabilnego punktu zaczepienia na wysokości klatki piersiowej.'],
    ['0979', 'Прикрепите ремешок к прочной точке крепления на высоте талии.', 'Прикрепите ленту к прочной точке крепления на уровне груди.'],
    ['0979', 'Bandı bel yüksekliğinde sağlam bir bağlantı noktasına takın.', 'Bandı göğüs yüksekliğinde sağlam bir bağlantı noktasına takın.'],
    ['0979', '将带子固定在腰部高度的坚固锚点上。', '将带子固定在胸部高度的坚固锚点上。'],
    ['0979', 'напрягите мышцы кора ​​и сохраняйте устойчивую позицию.', 'Напрягите мышцы кора и сохраняйте устойчивое положение.'],
    ['3666', 'Постепенно уменьшайте наклон и скорость беговой дорожки, чтобы она остыла перед остановкой.', 'Постепенно уменьшайте наклон и скорость дорожки, чтобы спокойно завершить тренировку и выполнить заминку.'],
    ['2138', 'Задействуйте основные мышцы, чтобы поддерживать устойчивость и правильную осанку.', 'Задействуйте мышцы кора, чтобы поддерживать устойчивость и правильную осанку.'],
    ['0009', 'Grasp the handles with your palms facing down and your arms fully extended.', 'Grasp the parallel handles with a neutral grip, palms facing each other, and begin with your elbows nearly extended.'],
    ['0594', 'Adjust the seat height so that your knees are slightly bent and your feet are flat on the footplate.', 'Adjust the machine so your knees are bent about 90 degrees, the balls of your feet rest on the platform, and your heels remain free to move.'],
    ['0770', 'Engage your core and unrack the barbell, stepping back to clear the rack.', 'Engage your core and rotate the bar to release the Smith machine hooks, keeping your feet planted and the bar inside the guide rails.'],
    ['0770', 'Activa el core y suelta la barra del soporte, dando un paso atrás para alejarte del soporte.', 'Activa el core y gira la barra para soltarla de los ganchos de la máquina Smith, manteniendo los pies firmemente apoyados y la barra dentro de los rieles guía.'],
    ['0770', 'Gaine ta sangle abdominale et sors la barre du rack, en reculant pour dégager le support.', "Gaine ta sangle abdominale et fais pivoter la barre pour la dégager des crochets de la machine Smith, en gardant les pieds bien ancrés au sol et la barre à l'intérieur des rails de guidage."],
    ['0770', 'अपने कोर को संलग्न करें और रैक को साफ़ करने के लिए पीछे हटते हुए बारबेल को खोलें।', 'अपने कोर को सक्रिय करें और स्मिथ मशीन के हुक खोलने के लिए बारबेल को घुमाएँ, अपने पैरों को ज़मीन पर टिकाए रखें और बारबेल को गाइड रेल के भीतर रखें।'],
    ['0770', "Coinvolgi il core e sblocca il bilanciere, facendo un passo indietro per liberare il rack.", "Coinvolgi il core e ruota il bilanciere per sganciarlo dai ganci della Smith Machine, mantenendo i piedi ben piantati e il bilanciere all'interno delle guide."],
    ['0770', '복부에 힘을 주고 바벨을 언래크하여 뒤로 물러 랙을 치웁니다.', '코어에 힘을 주고 바를 돌려 스미스 머신의 훅을 해제하며, 발은 바닥에 고정하고 바는 가이드 레일 안에 유지합니다.'],
    ['0770', 'Napnij mięśnie brzucha i zdejmij sztangę ze stojaka, robiąc krok w tył, aby ją uwolnić.', 'Napnij mięśnie brzucha i obróć sztangę, aby zwolnić ją z haków suwnicy Smitha, nie odrywając stóp od podłoża i utrzymując sztangę wewnątrz prowadnic.'],
    ['0770', 'Напрягите корпус и снимите штангу со стойки, отступив назад, чтобы освободить стойку.', 'Напрягите корпус и поверните гриф, чтобы снять его с крюков машины Смита, удерживая стопы на полу, а гриф — внутри направляющих.'],
    ['0770', 'Merkez bölgenizi devreye sokun ve halteri serbest bırakın, rafı temizlemek için geri adım atın.', 'Merkez bölgenizi devreye sokun ve halteri döndürerek Smith makinesinin kancalarından çıkarın; ayaklarınızı yere sabit basın ve halteri kılavuz rayların içinde tutun.'],
    ['0770', '启动你的核心并打开杠铃，后退以清理架子。', '收紧核心并转动杠铃，以解除史密斯机挂钩的锁定，同时保持双脚踩稳，并确保杠铃始终位于导轨内。'],
    ['0213', 'Grasp the v-bar attachment with an overhand grip, palms facing each other, and your hands shoulder-width apart.', 'Grasp the V-bar attachment with a neutral grip, palms facing each other.'],
    ['0213', 'Sujeta el accesorio en V con un agarre prono, con las palmas una frente a la otra y las manos separadas a la altura de los hombros.', 'Sujeta el accesorio en V con un agarre neutro, con las palmas una frente a la otra.'],
    ['0213', "Saisis la poignée en V avec une prise en pronation, les paumes tournées l'une vers l'autre, et les mains écartées à la largeur des épaules.", "Saisis la poignée en V avec une prise neutre, les paumes tournées l'une vers l'autre."],
    ['0213', 'वी-बार अटैचमेंट को ओवरहैंड ग्रिप से पकड़ें, हथेलियाँ एक-दूसरे के सामने हों और आपके हाथ कंधे की चौड़ाई से अलग हों।', 'वी-बार अटैचमेंट को न्यूट्रल ग्रिप से पकड़ें, हथेलियाँ एक-दूसरे की ओर रहें।'],
    ['0213', "Afferra l'attacco V-bar con una presa sopra la mano, palmi rivolti uno verso l'altro e mani alla larghezza delle spalle.", "Afferra l'attacco V-bar con una presa neutra, con i palmi rivolti uno verso l'altro."],
    ['0213', 'V바 어태치먼트를 오버그립으로 잡고 손가락이 서로를 향하며 손은 어깨너비만큼 벌립니다.', 'V바 어태치먼트를 뉴트럴 그립으로 잡고 손바닥이 서로 마주 보게 합니다.'],
    ['0213', 'Chwyć uchwyt w kształcie litery V nachwytem, dłonie zwrócone do siebie, rozstawione na szerokość barków.', 'Chwyć uchwyt w kształcie litery V chwytem neutralnym, z dłońmi zwróconymi do siebie.'],
    ['0213', 'Возьмитесь за насадку V-образной перекладины хватом сверху, ладони обращены друг к другу, руки на ширине плеч.', 'Возьмитесь за V-образную рукоять нейтральным хватом, ладонями друг к другу.'],
    ['0213', "V-bar aparatını üstten kavrayarak, avuçlarınız birbirine bakacak şekilde ve elleriniz omuz genişliğinde açık olacak şekilde kavrayın.", "V-bar aparatını nötr tutuşla, avuç içleriniz birbirine bakacak şekilde kavrayın."],
    ['0213', '正手握住 V 形杆附件，手掌相对，双手与肩同宽。', '以中立握法握住 V 形手柄，双掌相对。'],
    ['0238', 'Grasp the bar with an overhand grip, keeping your arms straight and your palms facing down.', 'Grasp the bar with an overhand grip, keeping a soft bend in your elbows and your palms facing down.'],
    ['0238', 'Engage your lats and pull the bar down towards your thighs, keeping your arms straight throughout the movement.', 'Engage your lats and pull the bar down towards your thighs, keeping the same slight elbow bend throughout the movement.'],
    ['0238', 'Sujeta la barra con un agarre prono, manteniendo los brazos rectos y las palmas hacia abajo.', 'Sujeta la barra con un agarre prono, manteniendo una ligera flexión en los codos y las palmas hacia abajo.'],
    ['0238', 'Activa los dorsales y tira de la barra hacia abajo, hacia los muslos, manteniendo los brazos rectos durante todo el movimiento.', 'Activa los dorsales y tira de la barra hacia los muslos, manteniendo la misma ligera flexión de los codos durante todo el movimiento.'],
    ['0238', 'Saisis la barre avec une prise en pronation, en gardant tes bras tendus et tes paumes tournées vers le bas.', 'Saisis la barre avec une prise en pronation, en gardant les coudes légèrement fléchis et les paumes vers le bas.'],
    ['0238', "Contracte tes grands dorsaux et tire la barre vers le bas jusqu'à tes cuisses, en gardant les bras tendus pendant tout le mouvement.", 'Contracte tes grands dorsaux et tire la barre vers tes cuisses, en conservant la même légère flexion des coudes pendant tout le mouvement.'],
    ['0238', 'अपनी बाहों को सीधा रखते हुए और अपनी हथेलियों को नीचे की ओर रखते हुए, बार को ओवरहैंड ग्रिप से पकड़ें।', 'बार को ओवरहैंड ग्रिप से पकड़ें, कोहनियों में हल्का मोड़ रखें और हथेलियाँ नीचे की ओर रखें।'],
    ['0238', 'अपनी लेट्स को संलग्न करें और बार को अपनी जांघों की ओर नीचे खींचें, अपनी भुजाओं को पूरे आंदोलन के दौरान सीधा रखें।', 'अपने लैट्स को सक्रिय करें और कोहनियों का वही हल्का मोड़ बनाए रखते हुए बार को अपनी जांघों की ओर नीचे खींचें।'],
    ['0238', 'Afferra la barra con una presa sopra la mano, tenendo le braccia dritte e i palmi rivolti verso il basso.', 'Afferra la barra con una presa prona, mantenendo i gomiti leggermente piegati e i palmi rivolti verso il basso.'],
    ['0238', 'Attiva i dorsali e tira la barra verso le cosce, mantenendo le braccia dritte durante tutto il movimento.', 'Attiva i dorsali e tira la barra verso le cosce, mantenendo la stessa leggera flessione dei gomiti per tutto il movimento.'],
    ['0238', '오버그립으로 바를 잡고 팔을 곧게 펴서 손바닥이 아래를 향하게 합니다.', '오버그립으로 바를 잡고 팔꿈치는 살짝 굽힌 채 손바닥이 아래를 향하게 합니다.'],
    ['0238', '광배근을 단련하여 팔을 곧게 유지하면서 바를 천천히 허벅지 쪽으로 당깁니다.', '광배근에 힘을 주고 팔꿈치의 같은 미세한 굽힘을 유지하면서 바를 허벅지 쪽으로 내립니다.'],
    ['0238', 'Chwyć drążek chwytem nachwytem, trzymając ramiona proste, dłonie skierowane w dół.', 'Chwyć drążek nachwytem, utrzymując lekko ugięte łokcie i dłonie skierowane w dół.'],
    ['0238', 'Napnij mięśnie najszersze i przyciągnij drążek w dół w kierunku ud, utrzymując ramiona wyprostowane przez cały czas ruchu.', 'Napnij mięśnie najszersze i przyciągnij drążek w dół w kierunku ud, zachowując przez cały ruch to samo lekkie ugięcie łokci.'],
    ['0238', 'Возьмите перекладину хватом сверху, держа руки прямыми и ладонями вниз.', 'Возьмитесь за перекладину хватом сверху, слегка согнув локти и направив ладони вниз.'],
    ['0238', 'Напрягите широчайшие и потяните штангу вниз к бедрам, сохраняя руки прямыми на протяжении всего движения.', 'Напрягите широчайшие и потяните перекладину к бёдрам, сохраняя одинаковый небольшой сгиб в локтях на протяжении всего движения.'],
    ['0238', 'Barı üstten kavrayarak, kollarınızı düz ve avuç içleriniz aşağıya bakacak şekilde tutun.', 'Barı üstten kavrayın; dirseklerinizi hafifçe bükülü, avuç içlerinizi aşağı dönük tutun.'],
    ['0238', 'Kollarınızı hareket boyunca düz tutarak barı uyluklarınıza doğru çekin.', 'Kanatlarınızı devreye sokup barı uyluklarınıza doğru çekerken dirseklerinizdeki hafif bükülmeyi hareket boyunca koruyun.'],
    ['0238', '正手握住杠铃，保持手臂伸直，手掌朝下。', '正手握住直杆，肘部保持轻微弯曲，掌心向下。'],
    ['0238', '收紧背阔肌并将杠铃向下拉向大腿，在整个运动过程中保持手臂伸直。', '收紧背阔肌，将直杆向下拉至大腿，同时在整个动作中保持肘部同样的轻微弯曲。'],
  ])('corrects %s instruction copy', (id, source, expected) => {
    expect(correctExerciseInstructions(id, [source])).toEqual([expected])
  })

  it.each([
    ['0274', 'Place your hands behind your head with your elbows pointing outwards.', 'Place your fingertips lightly behind your head with your elbows open; do not pull on your head or neck.'],
    ['0274', 'Engage your abs and lift your shoulders off the ground, curling forward towards your knees.', 'Brace your abs and curl your ribcage toward your pelvis, lifting only your shoulder blades while keeping your lower back on the floor.'],
    ['0274', 'Coloca las manos detrás de la cabeza con los codos apuntando hacia afuera.', 'Coloca suavemente las yemas de los dedos detrás de la cabeza, con los codos abiertos; no tires de la cabeza ni del cuello.'],
    ['0274', 'Activa el abdomen y levanta los hombros del suelo, flexionándote hacia adelante en dirección a las rodillas.', 'Activa el abdomen y acerca la caja torácica a la pelvis, levantando solo los omóplatos mientras mantienes la zona lumbar apoyada en el suelo.'],
    ['0274', "Place tes mains derrière ta tête avec tes coudes pointés vers l'extérieur.", "Place délicatement le bout de tes doigts derrière ta tête, les coudes écartés ; ne tire ni sur ta tête ni sur ton cou."],
    ['0274', "Gaine tes abdominaux et décolle tes épaules du sol, en t'enroulant vers l'avant en direction de tes genoux.", "Gaine tes abdominaux et enroule la cage thoracique vers le bassin, en soulevant uniquement les omoplates tout en gardant le bas du dos au sol."],
    ['0274', 'अपने हाथों को अपने सिर के पीछे रखें और अपनी कोहनियों को बाहर की ओर रखें।', 'अपनी उँगलियों के सिरों को सिर के पीछे हल्के से रखें और कोहनियों को खुला रखें; हाथों से सिर या गर्दन को न खींचें।'],
    ['0274', 'अपने पेट को संलग्न करें और अपने कंधों को जमीन से ऊपर उठाएं, अपने घुटनों की ओर आगे की ओर झुकें।', 'पेट को कसें और पसलियों के पिंजरे को श्रोणि की ओर मोड़ते हुए केवल कंधे की हड्डियों को फर्श से उठाएँ; पीठ का निचला हिस्सा फर्श पर टिका रहे।'],
    ['0274', "Metti le mani dietro la testa con i gomiti rivolti verso l'esterno.", 'Appoggia leggermente i polpastrelli dietro la testa, mantenendo i gomiti aperti; non tirare la testa o il collo con le mani.'],
    ['0274', 'Attiva gli addominali e solleva le spalle da terra, piegandosi in avanti verso le ginocchia.', 'Contrai gli addominali e avvicina la gabbia toracica al bacino, sollevando solo le scapole e mantenendo la zona lombare a contatto con il pavimento.'],
    ['0274', '손을 머리 뒤에 올려놓고 팔꿈치를 바깥쪽으로 향하게 합니다.', '손가락 끝을 머리 뒤에 가볍게 대고 팔꿈치를 벌린 상태로 유지합니다. 손으로 머리나 목을 당기지 않습니다.'],
    ['0274', '복부에 힘을 주어 어깨를 들어올리며 무릎 방향으로 몸을 굽힙니다.', '복부에 힘을 주고 흉곽을 골반 쪽으로 말아 올리면서 견갑골만 바닥에서 들어 올리고, 허리는 바닥에 붙인 상태를 유지합니다.'],
    ['0274', 'Umieść dłonie za głową, łokcie skierowane na zewnątrz.', 'Lekko oprzyj opuszki palców za głową, trzymając łokcie rozchylone; nie ciągnij za głowę ani za szyję.'],
    ['0274', 'Napnij mięśnie brzucha i unieś barki znad podłogi, zwijając tułów w kierunku kolan.', 'Napnij mięśnie brzucha i zwiń tułów, zbliżając klatkę piersiową do miednicy; unieś tylko łopatki, a dolną część pleców pozostaw na podłodze.'],
    ['0274', 'Положите руки за голову локтями наружу.', 'Слегка коснитесь затылка кончиками пальцев и разведите локти в стороны; не тяните руками голову или шею.'],
    ['0274', 'Напрягите пресс и поднимите плечи от земли, наклонившись вперед к коленям.', 'Напрягите пресс и скрутите корпус, направляя грудную клетку к тазу; отрывайте от пола только лопатки и сохраняйте поясницу прижатой к полу.'],
    ['0274', 'Ellerinizi başınızın arkasına, dirsekleriniz dışarı bakacak şekilde yerleştirin.', 'Parmak uçlarınızı başınızın arkasına hafifçe yerleştirin ve dirseklerinizi açık tutun; ellerinizle başınızı veya boynunuzu çekmeyin.'],
    ['0274', 'Karın kaslarınızı devreye sokun ve omuzlarınızı yerden kaldırın, dizlerinize doğru öne doğru kıvrılın.', 'Karın kaslarınızı sıkın ve göğüs kafesinizi pelvisinize doğru kıvırın; yalnızca kürek kemiklerinizi yerden kaldırın ve belinizi yerde tutun.'],
    ['0274', '将双手放在脑后，肘部朝外。', '将指尖轻放在脑后，保持肘部向外打开；不要用手拉扯头部或颈部。'],
    ['0274', '收紧腹肌，将肩膀抬离地面，向前向膝盖弯曲。', '收紧腹肌，将胸廓向骨盆方向卷曲，只抬起肩胛骨，同时保持下背部贴在地面上。'],
    ['0620', 'Pause for a moment at the top, then slowly lower your legs back down to the starting position.', 'Pause briefly at the top. Keeping your abs braced and your lower back gently pressed into the bench, slowly lower your joined legs only as far as you can without your lower back lifting or arching.'],
    ['0620', 'Haz una pausa por un momento en la parte superior, luego baja lentamente las piernas de vuelta a la posición inicial.', 'Haz una breve pausa en la parte superior. Mantén el abdomen activado y la zona lumbar suavemente apoyada contra el banco; baja lentamente las piernas juntas solo hasta donde puedas sin que la zona lumbar se despegue ni se arquee.'],
    ['0620', 'Marque une pause en haut, puis abaisse lentement tes jambes pour revenir à la position de départ.', "Marque une courte pause en haut. Garde les abdominaux gainés et le bas du dos légèrement plaqué contre le banc, puis abaisse lentement les jambes jointes uniquement jusqu'au point où le bas du dos ne se décolle ni ne se cambre."],
    ['0620', 'शीर्ष पर एक पल के लिए रुकें, फिर धीरे-धीरे अपने पैरों को वापस प्रारंभिक स्थिति में ले आएं।', 'ऊपर थोड़ी देर रुकें। पेट को कसकर रखें और पीठ के निचले हिस्से को बेंच पर हल्के से टिकाए रखें; दोनों पैरों को साथ रखते हुए धीरे-धीरे केवल उतना ही नीचे लाएँ, जितना पीठ के निचले हिस्से को बेंच से उठने या कमर में मेहराब बनने दिए बिना संभव हो।'],
    ['0620', 'Fai una pausa per un momento in alto, quindi abbassa lentamente le gambe fino alla posizione di partenza.', 'Fai una breve pausa in alto. Mantieni gli addominali contratti e la zona lombare leggermente premuta contro la panca; abbassa lentamente le gambe unite solo fin dove riesci senza che la zona lombare si sollevi o si inarchi.'],
    ['0620', '맨 위에서 잠깐 멈춘 후 천천히 다리를 처음 위치로 내립니다.', '최고 지점에서 잠시 멈춥니다. 복부에 힘을 주고 허리 아래쪽을 벤치에 가볍게 밀착한 상태를 유지하면서, 허리 아래쪽이 들리거나 휘지 않는 범위까지만 두 다리를 붙인 채 천천히 내립니다.'],
    ['0620', 'Zatrzymaj się na chwilę w górnej pozycji, a następnie powoli opuść nogi do pozycji wyjściowej.', 'Zatrzymaj się krótko w górnej pozycji. Utrzymując napięte mięśnie brzucha i lekko dociskając dolną część pleców do ławki, powoli opuszczaj złączone nogi tylko tak nisko, aby dolna część pleców nie odrywała się od ławki ani nie wyginała się.'],
    ['0620', 'Задержитесь на мгновение в верхней точке, затем медленно опустите ноги обратно в исходное положение.', 'Коротко задержитесь в верхней точке. Удерживая пресс напряжённым, а поясницу слегка прижатой к скамье, медленно опустите соединённые ноги только настолько, насколько можете сделать это без отрыва или прогиба поясницы.'],
    ['0620', 'Tepe noktasında bir an duraklayın, ardından bacaklarınızı yavaşça başlangıç\u200b\u200bpozisyonuna indirin.', 'Tepe noktasında kısa süre duraklayın. Karın kaslarınızı sıkı ve belinizi sehpaya hafifçe bastırılmış halde tutarak, bacaklarınızı bitişik tutup beliniz sehpadan kalkmadan veya çukurlaşmadan yalnızca kontrol edebildiğiniz kadar yavaşça indirin.'],
    ['0620', '在顶部暂停片刻，然后慢慢将双腿放回起始位置。', '在顶部短暂停顿。保持腹肌收紧、下背部轻贴长凳，然后缓慢下放并拢的双腿，只降到下背部不会离开长凳或拱起的高度。'],
    ['0872', 'Напрягите пресс и оторвите бедра от пола, подтягивая колени к груди.', 'Напрягите пресс, подкрутите таз и слегка оторвите его от пола, направляя колени к груди.'],
    ['0872', 'Задержитесь на мгновение в верхней точке, затем медленно опустите бедра обратно в исходное положение.', 'Задержитесь на мгновение в верхней точке, затем медленно опустите таз обратно в исходное положение.'],
    ['0705', 'Напрягите корпус и поднимите бедра от земли, создавая прямую линию от головы до ступней.', 'Напрягите корпус и поднимите таз над полом, выстраивая прямую линию от головы до стоп.'],
    ['0705', 'Опустите бедра обратно в исходное положение.', 'Опустите таз обратно в исходное положение.'],
  ])('corrects bodyweight core guidance for %s', (id, source, expected) => {
    expect(correctExerciseInstructions(id, [source])).toEqual([expected])
  })

  it('leaves unrelated and custom instructions unchanged', () => {
    const steps = ['Keep this instruction verbatim.']
    expect(correctExerciseInstructions('custom-1', steps)).toEqual(steps)
  })
})
